### ISSUE TITLE
Some fonts show up with the bottom cut off

### ISSUE THREAD

**Issue by rishabh-bector** [4ydx/gltext#10]
Is this because of the errors with freetype heights? Is there a way to fix this manually, such as specifying a custom offset of some sort? Here's an example of some text rendered which causes problems:

![capture](https://user-images.githubusercontent.com/7831335/47260665-798fb480-d485-11e8-95ee-c9b14c687021.PNG)

This is rendered with debug mode on. It seems like the bounding rect is above the full text?

**Comment by 4ydx** [comment]
NewTruetypeFontConfig now has a parameter that allows you to adjust the height.  If you add height, this will hopefully resolve itself.

**Comment by rishabh-bector** [comment]
That's very helpful - thank you!
