### ISSUE TITLE
Characters appear to be overlapping

### ISSUE THREAD

**Issue by willdougadams** [4ydx/gltext#9]
I am able to run the example without issue, but when I copy that same exact code over into my project, I am getting partial characters:

![screen shot 2018-03-06 at 12 05 49 pm](https://user-images.githubusercontent.com/9994041/37056555-9f7187be-2139-11e8-8005-3ee2aeb5a655.png)

Have you seen this before?  It's in a project of mine [here](https://github.com/willdougadams/GOpenGL/blob/master/src/States/MenuState.go) which is being driven in a loop that holds states.  pseudo-loop:

    for !app.window.ShouldClose() {
        gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
        // this will update the state
        app.mr_manager.Update(float32(elapsed_seconds))
        // this will draw it
        app.mr_manager.Draw()
        app.window.SwapBuffers()
    }

I didn't write any text rendering code, I just moved code from `gltext/example/main.go` to my project.  Any ideas?

I'm on MacOS High Sierra 10.13.3, and I get the same on Linux Mint 13.3

**Comment by 4ydx** [comment]
I have pushed a change that alters how each rune quad is calculated.  Hopefully this doesn't fly in the face of how TTF is intended to be used.  Please try it and see if this helps with your issue.

On a deeper level I suspect that your blending is not functioning correctly.  Have you enabled/disabled something about the opengl blending state elsewhere in your code?

Also, I have added a debug method that will allow you to inspect the vbo data being generated to see if there is an issue there.  Simply set gltext.IsDebug = true before doing any rendering.  This will output the quads that are being created for each rune with their positions as well as their texture locations.

**Comment by willdougadams** [comment]
Thanks, that fixed it!  I'm an opengl novice, so I have no blending happening at all, nothing else I'm doing has transparency :(  If this breaks your kerning or anything and you switch it back, I'll look into blending to fix it.  Would that be as simple as `glEnable(GL_BLEND)` or would it also require an understanding of `glBlendFunc()`?

**Comment by 4ydx** [comment]
Well the way it is currently written it ought to be able to take care of itself.  Given that you haven't done something, it may well be that my use of blend is not fully functional across platforms.  For the moment I will consider this fixed and am hoping the change doesn't have unintended consequences.  Thanks for your feedback!

**Comment by willdougadams** [comment]
Awesome, thanks for the excellent tool :)
